### ISSUE TITLE
Join Hello.go and Greetings.go

### ISSUE THREAD

**Issue by krasi-georgiev** [YaniGalyov/First-Step#2]
please make 
https://github.com/YaniGalyov/First-Step/blob/52a3c740586b86e676f51841a873e5c38c4615d9/Greetings.go#L7-L11
as a  independent function called `Greeting` and put it in `Hello.go`.

Than in main func call the new `Greeting` function.
https://github.com/YaniGalyov/First-Step/blob/52a3c740586b86e676f51841a873e5c38c4615d9/Hello.go#L5-L7

**Comment by YaniGalyov** [comment]
Is this OK?

package main

import "fmt"

func main() {
	fmt.Println("First-Step")

	names := []string{"Yani", "Vlad", "Krasi", "Ivan", "Kris", "Naso", "Dimi", "Geri", "Lili", "Zoya"}

	for _, c := range names {
		fmt.Println("Name:", c)
	}
}
